apiVersion: v1
kind: Service
metadata:
  name: network-service
spec:
  selector:
    app: network
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: app
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090